# Generated by Django 4.0.2 on 2022-02-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_placement_app', '0002_remove_records_img_alter_records_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='package',
            field=models.FloatField(),
        ),
    ]
